### ISSUE TITLE
Pointerlock still failing to auto-publish

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#16]
It's reporting: 

```
 👎 not-authorized
```

**Comment by marcoscaceres** [comment]
@siusin, sorry, when you have a few minutes, could you please take a look again?

**Comment by siusin** [comment]
> "metadata": {
>       "previousVersion": "https://www.w3.org/TR/2016/REC-pointerlock-20161027/",
>       "cfe": false,
>       "editors": [
>         92361
>       ]

@deniak Looks like [Echidna is taking it as a FPWD](https://labs.w3.org/echidna/api/status?id=2395195a-2f94-485a-a424-6ab108bcc5d5), but we did publish a [WD in June](https://www.w3.org/TR/pointerlock-2/). Any idea how to fix it?

**Comment by deniak** [comment]
I see at least 2 errors here:

1. the shortname in the [manifest](https://w3c.github.io/pointerlock/ECHIDNA) is wrong. Since you are using the shortname `pointerlock`, spec-generator will take the REC as the previous version. The manifest should be updated with the shortname `pointerlock-2`
2. the error reported by echidna means you aren't using the right token. I see it was updated 6 days ago. @siusin I'll send you the token in privmsg. Please re-encrypt it and update the manifest.

**Comment by siusin** [comment]
Yep, it was because we forgot to update the shortname in the manifest. Thanks Denis!

**Comment by marcoscaceres** [comment]
Yay! thank you for fixing it!
