### ISSUE TITLE
W3C WebApps page shows our group as closed

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappswg#26]
I know this is the "2008" group, but anyone searching for "WebApps WG" always ends up there:
https://www.w3.org/2008/webapps/

That should contain the current group's information, or maybe we can delete that page entirely? 

@ylafon @siusin wdty?

**Comment by marcoscaceres** [comment]
And https://www.w3.org/WebPlatform/WG/ should point to our new WG :) because Web Platform homepage just takes you to a dead end.

**Comment by siusin** [comment]
My understanding is we can't delete the 2008 WebApps WG because its list of patent disclosure is different from the current WebApps WG. The Web Platform WG is still valid because WebIDL is in that group and we are waiting for Process 2020 to find a new place for WebIDL.

@plehegar  any suggestion to improve these issues?

**Comment by plehegar** [comment]
The page is linked from some of our specs so I wouldn't recommend deleting it. We could:
1.  redirect to the proper page
2. or update the warning at the top of point to the proper page

For WebPlatform, I concur that we have a warning to point to WebApps instead. The fact that the Group is still open is more of unresolved "bug" than anything.

**Comment by marcoscaceres** [comment]
For xmas, and having been good all year, I'd really prefer 1 please. 🎁🎄

**Comment by siusin** [comment]
Done. Now both https://www.w3.org/2008/webapps/ and https://www.w3.org/WebPlatform/WG/ point to the WebApps WG homepage.
